name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        sdk: [csgo, tf2]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: 'sourcemod'
          
      - name: download submodules
        run: |
          cd sourcemod
          git submodule update --init --recursive
        
      - name: download ${{ matrix.sdk }} sdk
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: ${{ matrix.sdk }}
          path: hl2sdk-${{ matrix.sdk }}
        
      - name: download metamod
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/metamod-source
          ref: 1.10-dev
          path: 'mmsource-1.10'
        
      - name: download ambuild
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/ambuild
          path: 'ambuild'
        
      - name: install ambuild
        if: runner.os == 'Windows'
        run: |
          cd ambuild
          python setup.py install
        
      - name: install ambuild
        if: runner.os == 'Linux'
        run: |
          cd ambuild
          sudo python setup.py install
          
      - name: install linux packages
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y --no-install-recommends gcc-multilib g++-multilib
        
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
        with:
          arch: x86
        
      - name: configure ambuild
        run: |
          cd sourcemod
          mkdir build
          cd build
          python ../configure.py --sdks ${{ matrix.sdk }} --no-mysql
              
      - name: build
        run: |
          cd sourcemod/build
          ambuild
        
      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-${{ matrix.sdk }}-${{ github.sha }}
          path: sourcemod/build/package/
