name: buildall

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: 'sourcemod'
          
      - name: download submodules
        run: |
          cd sourcemod
          git submodule update --init --recursive
        
      - name: download proxy sdk
        run: git clone --mirror https://github.com/alliedmodders/hl2sdk hl2sdk-proxy-repo
          
      - name: download csgo sdk
        run: git clone hl2sdk-proxy-repo hl2sdk-csgo -b csgo
        
      - name: download hl2dm sdk
        run: git clone hl2sdk-proxy-repo hl2sdk-hl2dm -b hl2dm
        
      - name: download nucleardawn sdk
        run: git clone hl2sdk-proxy-repo hl2sdk-nucleardawn -b nucleardawn
        
      - name: download l4d2 sdk
        run: git clone hl2sdk-proxy-repo hl2sdk-l4d2 -b l4d2
        
      - name: download dods sdk
        run: git clone hl2sdk-proxy-repo hl2sdk-dods -b dods
        
      - name: download l4d sdk
        run: git clone hl2sdk-proxy-repo hl2sdk-l4d -b l4d
        
      - name: download css sdk
        run: git clone hl2sdk-proxy-repo hl2sdk-css -b css
        
      - name: download tf2 sdk
        run: git clone hl2sdk-proxy-repo hl2sdk-tf2 -b tf2
        
      - name: download insurgency sdk
        run: git clone hl2sdk-proxy-repo hl2sdk-insurgency -b insurgency
        
      - name: download sdk2013 sdk
        run: git clone hl2sdk-proxy-repo hl2sdk-sdk2013 -b sdk2013
        
      - name: download doi sdk
        run: git clone hl2sdk-proxy-repo hl2sdk-doi -b doi
        
      - name: download metamod
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/metamod-source
          ref: 1.10-dev
          path: 'mmsource-1.10'
        
      - name: download ambuild
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/ambuild
          path: 'ambuild'
        
      - name: install ambuild
        if: runner.os == 'Windows'
        run: |
          cd ambuild
          python setup.py install
        
      - name: install ambuild
        if: runner.os == 'Linux'
        run: |
          cd ambuild
          sudo python setup.py install
          
      - name: install linux packages
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y --no-install-recommends gcc-multilib g++-multilib
        
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
        with:
          arch: x86
        
      - name: configure ambuild
        run: |
          cd sourcemod
          mkdir build
          cd build
          python ../configure.py --sdks ${{ matrix.sdk }} --no-mysql
              
      - name: build
        run: |
          cd sourcemod/build
          ambuild
        
      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-${{ matrix.sdk }}-${{ github.sha }}
          path: sourcemod/build/package/
